// API Version
export const API_VERSION = 'v1';

// Rate limiting
export const RATE_LIMITS = {
  NEW_ADDRESS_PER_IP_PER_HOUR: 10,
  GET_MAILS_PER_MINUTE: 60,
  SEND_MAIL_PER_HOUR: 20,
};

// Pagination
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

// JWT
export const JWT_EXPIRY_DAYS = 30;
export const JWT_REFRESH_THRESHOLD_DAYS = 7;

// Address
export const ADDRESS_NAME_MIN_LENGTH = 3;
export const ADDRESS_NAME_MAX_LENGTH = 30;
export const ADDRESS_PASSWORD_MIN_LENGTH = 4;

// Email
export const MAX_EMAIL_SIZE = 25 * 1024 * 1024; // 25MB
export const MAX_ATTACHMENT_SIZE_DEFAULT = 5 * 1024 * 1024; // 5MB

// Cleanup
export const CLEANUP_DEFAULT_DAYS = 7;

// Error codes
export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ROLE_LIMIT_REACHED: 'ROLE_LIMIT_REACHED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  ADDRESS_EXISTS: 'ADDRESS_EXISTS',
  INVALID_ADDRESS_NAME: 'INVALID_ADDRESS_NAME',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  MAIL_NOT_FOUND: 'MAIL_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  CAPTCHA_FAILED: 'CAPTCHA_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

// HTTP Status codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
} as const;
